### PR TITLE
add icons

### PR DESCRIPTION
**Pull request by River-Mochi**
add icons

### CODE REVIEW

**Comment by Spagett1** [comment]
Ive made some major changes which conflict with these, would you mind clearing up the conflicts?

**Comment by Spagett1** [comment]
Ive also set all existing icons from the simpleicons to be #4E5EE4 as they do not show up at all otherwise if dark more is enabled, while im not set on the exact colour a colour is needed for them other than black.

**Comment by River-Mochi** [comment]
> 

I made them all black from simple icons for consistency.  for example Linux Penguin defaults to yellow which is very hard to see on White background.  if you remove the "color"  from each one like the black, then you can see the default color of the simple icon. 

their default colors are also listed here 
https://simpleicons.org/

**Comment by Spagett1** [comment]
Yeah, ive set all the simpleicons to #4E5EE4 as it is readable on both light and dark mode.

**Comment by Spagett1** [comment]
Great thanks

**Pull request merged**
